{% set version = "1.0.32" %}

package:
  name: wabt
  version: {{ version }}

source:
  url: https://github.com/WebAssembly/wabt/releases/download/{{ version }}/wabt-{{ version }}.tar.xz
  sha256: 8432925aa0fc22f52b94ea042784be1eb94733fbc29ef8a70f22f0c0822cf3a3

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - python
  host:

test:
  commands:
    - spectest-interp --help
    - wasm-interp --help
    - wasm-objdump --help
    - wasm-opcodecnt --help
    - wasm-validate --help
    - wasm2c --help
    - wasm2wat --help
    - wast2json --help
    - wat-desugar --help
    - wat2wasm --help

about:
  home: https://github.com/WebAssembly/wabt
  license: Apache-2.0
  license_file: LICENSE
  summary: The WebAssembly Binary Toolkit

extra:
  recipe-maintainers:
    - jakirkham
