{% set version = "1.0.19" %}

package:
  name: wabt
  version: {{ version }}

source:
  fn: wabt-{{ version }}.tar.gz
  url: https://github.com/WebAssembly/wabt/archive/{{ version }}.tar.gz
  sha256: 134f2afc8205d0a3ab89c5f0d424ff3823e9d2769c39d2235aa37eba7abc15ba

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - python 2.7.*
  host:

test:
  commands:
    - spectest-interp --help
    - wasm-interp --help
    - wasm-objdump --help
    - wasm-opcodecnt --help
    - wasm-validate --help
    - wasm2c --help
    - wasm2wat --help
    - wast2json --help
    - wat-desugar --help
    - wat2wasm --help

about:
  home: https://github.com/WebAssembly/wabt
  license: Apache-2.0
  license_file: LICENSE
  summary: The WebAssembly Binary Toolkit

extra:
  recipe-maintainers:
    - jakirkham
