{% set version = "1.0.36" %}

package:
  name: wabt
  version: {{ version }}

source:
  url: https://github.com/WebAssembly/wabt/releases/download/{{ version }}/wabt-{{ version }}.tar.xz
  sha256: aaf2515431912e191561b9d82df98850394af80e48076960161e09704a5ef7c6

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - python
  host:
    - openssl
  run:

test:
  commands:
    - spectest-interp --help
    - wasm-interp --help
    - wasm-objdump --help
    - wasm-stats --help
    - wasm-validate --help
    - wasm2c --help
    - wasm2wat --help
    - wast2json --help
    - wat-desugar --help
    - wat2wasm --help

about:
  home: https://github.com/WebAssembly/wabt
  license: Apache-2.0
  license_file: LICENSE
  summary: The WebAssembly Binary Toolkit

extra:
  recipe-maintainers:
    - jakirkham
