{% set version = "1.0.11" %}

package:
  name: wabt
  version: {{ version }}

source:
  fn: wabt-{{ version }}.tar.gz
  url: https://github.com/WebAssembly/wabt/archive/{{ version }}.tar.gz
  sha256: 90e7f4a4e924e38af4edb6ca298ade662869c5b61a12399e71ee53d598d52cbe

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja
    - python 2.7.*
  host:

test:
  commands:
    - spectest-interp --help
    - wasm-interp --help
    - wasm-objdump --help
    - wasm-opcodecnt --help
    - wasm-validate --help
    - wasm2c --help
    - wasm2wat --help
    - wast2json --help
    - wat-desugar --help
    - wat2wasm --help

about:
  home: https://github.com/WebAssembly/wabt
  license: Apache 2.0
  license_file: LICENSE
  summary: The WebAssembly Binary Toolkit

extra:
  recipe-maintainers:
    - jakirkham
