travis:
  secure:
    BINSTAR_TOKEN: YRWIljvB5k2+FqtpZoHdgV4GfoN/mYkBbCZieSLMh+pCctrJsDZBGBy456/NgnTzS6ehNDiD/DBLcr8hq3hicwPJHBGdAH2WmDwXguR0kmRdHRrq4dnKL/pMe3PpwgiNZGQDzM2bFCrUcTpz91ANrjvwe45/6gQYawModGAu95qebnASKlXkaK7BnSyfWZuedch8GBp+zaheok7aWdg+7hlPKkfniICemL9NyPAKlsHGq/ikCotuKICykXuHS6JnUryDqQz12f/Ghtb2wcFruBurlaNJAeTWkl7+tlTv/Ep7dttidpmiaZgTV4k74oCasFo+UTaNT4+DGqSEU/s4fxSY25P9aMvMzYMa+NkQfftc3rQtGwnbr1a0fS++Vj1J0kXNWdQRNh4JMbi42fFhIuq5m+ZInsKo95PQOyR/q31PtYsiyGpU7nv5tIw3MNhQ0RRZLDFpOcj5feRUQwmaLdeUQqRnJrpqplPyqcCaDHLL7ixxpoxaLHbYWFaZpHgxzzq2FbRqUFr1b57DEzdHbjYvs41vXx9cJ1/KGR4D7L/Ih8iwnn8vZjU40QCbGJjraQrNUDUumrXOerUHn7vNQRCh3t5F5QbhfOPYEjJUCV6maVhk9gh1NSGgO/UyALfoLY+A3W78EgixsqWFvcajyXx6siIQlb2nWBrKfI1oju8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
